/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.phicomm.t1zoom;

public final class R {
  public static final class id {
    public static final int btn_reset=0x7f010000;
    public static final int btn_smart_stretch=0x7f010001;
    public static final int btn_zoom_125=0x7f010002;
    public static final int tv_ip=0x7f010003;
  }
  public static final class layout {
    public static final int activity_main=0x7f020000;
  }
  public static final class string {
    public static final int app_name=0x7f030000;
  }
}